#@AspNetBlog.Api_HostAddress = https://localhost:7117
#@AspNetBlog.Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzQ1Njk5OTMxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNS80LzI2IDIxOjM4OjUwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTc0NTY3MTEzMCwiZXhwIjoxNzQ1Njc0NzMwLCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.GetoRScbRjg_4RRIvmWYVrSEJCyxi0rWLvbd5D8J1w8

GET {{AspNetBlog_Port}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AspNetBlog_Token}}

###

GET {{AspNetBlog_Port}}/api/User/Get
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}

###

GET {{AspNetBlog_Port}}/api/User/Get/1
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}

###

GET {{AspNetBlog_Port}}/api/Tenant/GetAll
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}