#@AspNetBlog.Api_HostAddress = https://localhost:7117
#@AspNetBlog.Token = 

GET {{AspNetBlog_Port}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/User/Get
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/User/Get/1
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/Tenant/GetAll
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/Tenant/MultiBusinessByTable
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/Tenant/SubLibraryBusinessTable
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/Tenant/GetTenantCache
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}
###
GET {{AspNetBlog_Port}}/api/Tenant/AddTenant
Accept: application/json
Authorization:Bearer {{AspNetBlog_Token}}